### PR TITLE
Wrap `evalMaybeM` and `evalEitherM` in `withFrozenCallStack`

### LINKED ISSUE #497: `evalMaybeM` doesn't produce the correct callstack
If we use `evalMaybeM` we get `the value was Nothing`, but it's not attached to the line calling `evalMaybeM`. I think `evalMaybeM` needs a `withFrozenCallStack`, but I'm not quite sure where - probably around the whole definition?

### PR DESCRIPTION
**Pull request by ocharles**
Fixes #497

### CODE REVIEW

**Comment by moodmosaic** [comment]
LGTM 👍 Do you think we could add some (reliable, trustworthy) test(s) for this change?

**Review by moodmosaic — COMMENTED** [review]
LGTM 👍 Do you think we could add some (reliable, trustworthy) test(s) for this change?

**Comment by ocharles** [comment]
I don't think I'm likely to find the time to do anymore work on this, sorry.

**Comment by moodmosaic** [comment]
No worries 👍

**Pull request merged**
