### PR TITLE
Release 0.4

### PR DESCRIPTION
**Pull request by jystic**
The state machine stuff is still a bit experimental, but we'll never get it solid if we don't use it, time for a release! 🔥

### CODE REVIEW

**Comment by charleso** [comment]
🎂

**Comment by moodmosaic** [comment]
Good idea! 💯

**Comment by jystic** [comment]
:shipit: [0.4](http://hackage.haskell.org/package/hedgehog-0.4)

**Comment by moodmosaic** [comment]
It'll be now slightly faster/easier to test #89 🎉

**Pull request merged**
