### PR TITLE
Add better TraversableB documentation including deprecation warning for HTraversable

### PR DESCRIPTION
**Pull request by jacobstanley**
Added an example showing how to derive `TraversableB` and a warning if you try to use `HTraversable`.

Hopefully that makes the upgrade process a bit easier.

Any suggestions welcome.

### CODE REVIEW

**Comment by ocharles** [comment]
Note that with `DeriveAnyClass` you don't need extra `instance` lines

**Comment by jacobstanley** [comment]
It's true but `DeriveAnyClass` has other side effects which aren't ideal so I wasn't sure about recommending it.

Ideally we could do it with `DerivingVia`.

**Comment by jacobstanley** [comment]
I originally had two examples, one using `DeriveAnyClass`, perhaps I'll go back to that.

**Comment by ocharles** [comment]
Personally I advise my colleagues to use DeriveAnyClass with DervingStrategies. Best of all works then!

**Comment by jacobstanley** [comment]
I think the syntax for `via` is a bit nicer, but I couldn't figure out how to write the instance for `Default` (or whatever we'd call it)

```hs
data Register v =
  Register Name (Var Pid v)
  deriving (Eq, Show, Generic)
  deriving (FunctorB, TraversableB) via (Default Register)
```

**Comment by ocharles** [comment]
While I do agree, I think it might be best if a library like `hedgehog` avoids introducing something like `Default`. Let's just stick to what we're good at, which is property testing :)

**Comment by jacobstanley** [comment]
Yeah I agree, I plan to add the `anyclass` example for this PR.

I don't think another solution is impossible longer term though, a few ideas:
- It could be another library, I use [quiet](https://hackage.haskell.org/package/quiet-0.2/docs/Quiet.html) for many of my show instances so that they're easier to read in tests.
- There is such a type [Default1](https://hackage.haskell.org/package/generic-deriving-1.14/docs/Generics-Deriving-Default.html#t:Default1) already but I think it has the wrong kind. If it was polykinded it would probably work. Of course you'd need the instance to be in `barbies` or `generic-deriving` then.

**Pull request merged**
