### PR TITLE
Copy and paste LICENSE rather than using symlinks

### PR DESCRIPTION
**Pull request by gwils**
I've also updated the copyright years.

### CODE REVIEW

**Comment by thumphries** [comment]
Why remove the symlinks? They're only there so that Hackage releases get the appropriate license, and `cabal sdist` follows the link just fine

**Comment by gwils** [comment]
It's breaking my nix tooling when I `fetchFromGithub` and then try to `callCabal2nix`. Hedgehog doesn't officially support nix so this is more of a favour than anything.
I've talked to Jacob about this and he is cool with it.

**Comment by thumphries** [comment]
Cool, sorry for the pushback, was missing context

**Comment by gwils** [comment]
Thanks!

**Pull request merged**
