### PR TITLE
Support GHC-9.6

### LINKED ISSUE #480: Support GHC-9.6 (template-haskell-2.20)
The current revision of hedgehog-1.2 rejects template-haskell-2.20 which is the version shipped with GHC-9.6. It would be nice if hedgehog supported this version of template-haskell such that this new GHC version is supported.

### PR DESCRIPTION
**Pull request by ysangkok**
Fixes #480

### CODE REVIEW

**Comment by moodmosaic** [comment]
Thank you! 🎯👍

**Comment by ysangkok** [comment]
@moodmosaic Should I make a PR to remove the 8.0 and 8.2 builds, or should they get fixed?

**Comment by ysangkok** [comment]
@moodmosaic I found out why the build was failing! The reason is that newer versions of `text` and `vector` don't work with the Haddock documentation generating shipped with older versions of GHC. So we don't need to remove these GHC versions, we just need to disable Haddocks for them. I reported submitted #482 which fixes the CI. That PR also links to the upstream bug report that I submitted. They are unwilling to work around this issue upstream, so we have to do it here.

**Comment by moodmosaic** [comment]
Awesome, @ysangkok. That seems to be the best option, after all:
>we don't need to remove these GHC versions entirely, we just need to disable Haddocks for them

Thank you 👍

**Pull request merged**
