### PR TITLE
Release 1.1.2 for compatibility with GHC 9.4 only

### PR DESCRIPTION
**Pull request by mbg**
As suggested/discussed over in https://github.com/qfpl/tasty-hedgehog/issues/61#issuecomment-1234009175, here's a branch for a possible 1.1.2 release that builds on [the last commit for the 1.1.1 release](https://github.com/hedgehogqa/haskell-hedgehog/commit/bf04960348d0a32aab9dc8ff39c93b7743fa1153) and cherry-picks https://github.com/hedgehogqa/haskell-hedgehog/commit/4a4d5634f8f5e1c2476796bb88cf22b2ba3c276e and https://github.com/hedgehogqa/haskell-hedgehog/commit/5a03c900bf3d765ec5bf5739e4fc5d8fa0f4f0fd. **This should not actually be merged into `master`**, but should just be used for a Hackage release, although we might want to update the changelog in `master` to include this release / add this branch to this repository somewhere.

### CODE REVIEW

**Comment by moodmosaic** [comment]
Thank you, @mbg! I believe all we need is a tag 1.1.2 off of this branch, make a hackage candidate, and then a hackage release, and then probably close this without merging it. Sounds like a plan?

**Review by moodmosaic — COMMENTED** [review]
Thank you, @mbg! I believe all we need is a tag 1.1.2 off of this branch, make a hackage candidate, and then a hackage release, and then probably close this without merging it. Sounds like a plan?

**Comment by mbg** [comment]
Sounds good to me! It's a little annoying that the CI isn't running for this PR to sanity check everything, though.

**Comment by moodmosaic** [comment]
I think it's not running because of the 'conflicts' git reports.

**Comment by mbg** [comment]
That does seem to be the case. Perhaps you could create a branch for this based on https://github.com/hedgehogqa/haskell-hedgehog/commit/bf04960348d0a32aab9dc8ff39c93b7743fa1153 and then re-target this PR to it?

**Comment by moodmosaic** [comment]
Looks like a good idea. We can then delete it once the PR is closed.

**Comment by moodmosaic** [comment]
@mbg, done but still don't see the CI running.

**Comment by moodmosaic** [comment]
@mbg, perhaps the branch `release-1.1.1` must be added in the [ci.yaml](https://github.com/hedgehogqa/haskell-hedgehog/blob/70cf9fd0719e2d0ace1093cbe75673d7b9b4cf65/.github/workflows/ci.yaml) (temporary, as part of this PR).

**Comment by mbg** [comment]
I think there isn't an event to re-trigger the CI for a branch change (it is only fired for `opened` and `synchronize`, but not `edited`). I will push something to trigger it.

**Comment by moodmosaic** [comment]
Cool! There's the CI build. Thanks, @mbg. 👍

**Comment by moodmosaic** [comment]
Changes in hedgehog-example.cabal won't be included since `hedgehog-example` isn't published.

**Comment by moodmosaic** [comment]
Package candidate release is up and looks good to me. Can you also take a look @mbg? https://hackage.haskell.org/package/hedgehog-1.1.2/candidate

**Comment by moodmosaic** [comment]
If we're good with the package candidate then here are the next steps:

1. Close this PR
2. Delete `release-1.1.1` branch that was temporarily pushed for this PR
3. Publish hedgehog-1.1.2 from its candidate release
4. [`git checkout bf04960348d0a32aab9dc8ff39c93b7743fa1153`](https://github.com/hedgehogqa/haskell-hedgehog/commit/bf04960348d0a32aab9dc8ff39c93b7743fa1153)
5. [`git cherry-pick 55f2800db3f15b7ffa8d6e24a33432c0e139a502`](https://github.com/hedgehogqa/haskell-hedgehog/pull/464/commits/55f2800db3f15b7ffa8d6e24a33432c0e139a502)
6. `git tag -a 1.1.2`
7. Push the tag

**Comment by mbg** [comment]
LGTM. I downloaded the archive from Hackage and tested it with `tasty-hedgehog` with both the existing Stack resolver as well as a Cabal build using GHC-9.4 (only bumping the version bounds for dependencies where required); both worked fine. I am not spotting any issues with the package itself either.

**Comment by moodmosaic** [comment]
Cool 👍 I can publish it now, if that helps. We can deal with the rest over the next day(s).

**Comment by moodmosaic** [comment]
@mbg, new point release on previous major is now up: https://hackage.haskell.org/package/hedgehog-1.1.2

I'll put up a PR that just includes 1.1.2 in the CHANGELOG for now. I'm not entirely sure how to go back and tag 1.1.2 without rewriting the history (which wouldn't be a good thing to do on the master branch).

**Comment by moodmosaic** [comment]
Thank you for work (here and in `tasty-hedgehog`) 🍻 👍

**Pull request closed without merging**
