### PR TITLE
Update QuickCheck upper bounds

### PR DESCRIPTION
**Pull request by lehins**

### CODE REVIEW

**Review by moodmosaic — APPROVED** [review]
👍

**Comment by lehins** [comment]
@moodmosaic Sorry for bugging you again. Do you think you could make new release or at least a revision on hackage with this change? It is blocking us from getting newest version of QuickCheck on stackage.

**Comment by moodmosaic** [comment]
No problem. I was working on automating all the releases for all our repos but for this one I guess I'll do it manually tomorrow morning as it's turning into a blocker.

**Comment by moodmosaic** [comment]
Published new revision for [hedgehog-quickcheck-0.1.1](https://hackage.haskell.org/package/hedgehog-quickcheck-0.1.1/revisions/), @lehins.

**Comment by lehins** [comment]
Woohoo. Thank you!

**Pull request merged**
