### PR TITLE
Allow random 1.2

### PR DESCRIPTION
**Pull request by felixonmars**
Builds fine and all tests pass here.

### CODE REVIEW

**Comment by moodmosaic** [comment]
Thanks :+1: There are actually some [breaking changes in random 1.2](https://github.com/haskell/random/blob/master/CHANGELOG.md#breaking-changes) but IIRC those aren't affecting anything. I'll double check first.

**Review by moodmosaic — COMMENTED** [review]
Thanks :+1: There are actually some [breaking changes in random 1.2](https://github.com/haskell/random/blob/master/CHANGELOG.md#breaking-changes) but IIRC those aren't affecting anything. I'll double check first.

**Comment by moodmosaic** [comment]
FWIW, I've triggered another build.

**Comment by moodmosaic** [comment]
I had to bump also QC in hedgehog-test-laws.cabal so I forced-pushed to the branch.

**Comment by lehins** [comment]
@moodmosaic Sorry for bugging you, but any news on making a release or at least a revision with this change. It is blocking us from getting `random` into stackage builds: commercialhaskell/stackage#5474

**Comment by moodmosaic** [comment]
@lehins I was planning to do a release this week but I'll try to make it happen earlier. Thanks for the heads up 👍 💯

**Comment by moodmosaic** [comment]
Published new revision for [hedgehog-1.0.3](https://hackage.haskell.org/package/hedgehog-1.0.3/revisions/), @lehins.

**Pull request merged**
