### PR TITLE
 Avoid weak gamma values in Hedgehog.Internal.Seed

### PR DESCRIPTION
**Pull request by moodmosaic**
Resolves https://github.com/hedgehogqa/haskell-hedgehog/issues/191 ― See https://github.com/hedgehogqa/haskell-hedgehog/issues/191#issuecomment-391209131 ― ✔ Passes all dieharder tests. :neckbeard:
 
---

```
$ dieharder-input | dieharder -a -g 200
#=============================================================================#
#            dieharder version 3.31.1 Copyright 2003 Robert G. Brown          #
#=============================================================================#
   rng_name    |rands/second|   Seed   |
stdin_input_raw|  3.00e+07  |2424813648|
#=============================================================================#
        test_name   |ntup| tsamples |psamples|  p-value |Assessment
#=============================================================================#
   diehard_birthdays|   0|       100|     100|0.88800885|  PASSED  
      diehard_operm5|   0|   1000000|     100|0.19714083|  PASSED  
  diehard_rank_32x32|   0|     40000|     100|0.38815709|  PASSED  
    diehard_rank_6x8|   0|    100000|     100|0.94344462|  PASSED  
   diehard_bitstream|   0|   2097152|     100|0.96453841|  PASSED  
        diehard_opso|   0|   2097152|     100|0.06116614|  PASSED  
        diehard_oqso|   0|   2097152|     100|0.23506030|  PASSED  
         diehard_dna|   0|   2097152|     100|0.40548706|  PASSED  
diehard_count_1s_str|   0|    256000|     100|0.93024945|  PASSED  
diehard_count_1s_byt|   0|    256000|     100|0.37068664|  PASSED  
 diehard_parking_lot|   0|     12000|     100|0.35955403|  PASSED  
    diehard_2dsphere|   2|      8000|     100|0.99480570|  PASSED  
    diehard_3dsphere|   3|      4000|     100|0.90990947|  PASSED  
     diehard_squeeze|   0|    100000|     100|0.07403175|  PASSED  
        diehard_sums|   0|       100|     100|0.00188117|   WEAK   
        diehard_runs|   0|    100000|     100|0.86278014|  PASSED  
        diehard_runs|   0|    100000|     100|0.55399860|  PASSED  
       diehard_craps|   0|    200000|     100|0.72844871|  PASSED  
       diehard_craps|   0|    200000|     100|0.66463648|  PASSED  
 marsaglia_tsang_gcd|   0|  10000000|     100|0.21806049|  PASSED  
 marsaglia_tsang_gcd|   0|  10000000|     100|0.39660207|  PASSED  
         sts_monobit|   1|    100000|     100|0.40274382|  PASSED  
            sts_runs|   2|    100000|     100|0.65543595|  PASSED  
          sts_serial|   1|    100000|     100|0.39984641|  PASSED  
          sts_serial|   2|    100000|     100|0.12878157|  PASSED  
          sts_serial|   3|    100000|     100|0.32054279|  PASSED  
          sts_serial|   3|    100000|     100|0.92776893|  PASSED  
          sts_serial|   4|    100000|     100|0.88823427|  PASSED  
          sts_serial|   4|    100000|     100|0.95001042|  PASSED  
          sts_serial|   5|    100000|     100|0.15192563|  PASSED  
          sts_serial|   5|    100000|     100|0.30862638|  PASSED  
          sts_serial|   6|    100000|     100|0.82350748|  PASSED  
          sts_serial|   6|    100000|     100|0.97031733|  PASSED  
          sts_serial|   7|    100000|     100|0.47614863|  PASSED  
          sts_serial|   7|    100000|     100|0.30898843|  PASSED  
          sts_serial|   8|    100000|     100|0.47266871|  PASSED  
          sts_serial|   8|    100000|     100|0.07446469|  PASSED  
          sts_serial|   9|    100000|     100|0.05486187|  PASSED  
          sts_serial|   9|    100000|     100|0.34267304|  PASSED  
          sts_serial|  10|    100000|     100|0.73402378|  PASSED  
          sts_serial|  10|    100000|     100|0.89991549|  PASSED  
          sts_serial|  11|    100000|     100|0.91679991|  PASSED  
          sts_serial|  11|    100000|     100|0.12537296|  PASSED  
          sts_serial|  12|    100000|     100|0.99502899|   WEAK   
          sts_serial|  12|    100000|     100|0.56007136|  PASSED  
          sts_serial|  13|    100000|     100|0.24452691|  PASSED  
          sts_serial|  13|    100000|     100|0.11884602|  PASSED  
          sts_serial|  14|    100000|     100|0.54430001|  PASSED  
          sts_serial|  14|    100000|     100|0.75405497|  PASSED  
          sts_serial|  15|    100000|     100|0.32598548|  PASSED  
          sts_serial|  15|    100000|     100|0.37035555|  PASSED  
          sts_serial|  16|    100000|     100|0.99882550|   WEAK   
          sts_serial|  16|    100000|     100|0.51607634|  PASSED  
         rgb_bitdist|   1|    100000|     100|0.41313031|  PASSED  
         rgb_bitdist|   2|    100000|     100|0.02449850|  PASSED  
         rgb_bitdist|   3|    100000|     100|0.72811423|  PASSED  
         rgb_bitdist|   4|    100000|     100|0.99164240|  PASSED  
         rgb_bitdist|   5|    100000|     100|0.66028955|  PASSED  
         rgb_bitdist|   6|    100000|     100|0.32112062|  PASSED  
         rgb_bitdist|   7|    100000|     100|0.69304928|  PASSED  
         rgb_bitdist|   8|    100000|     100|0.76816554|  PASSED  
         rgb_bitdist|   9|    100000|     100|0.38328541|  PASSED  
         rgb_bitdist|  10|    100000|     100|0.90157436|  PASSED  
         rgb_bitdist|  11|    100000|     100|0.25196359|  PASSED  
         rgb_bitdist|  12|    100000|     100|0.65831596|  PASSED  
rgb_minimum_distance|   2|     10000|    1000|0.84039186|  PASSED  
rgb_minimum_distance|   3|     10000|    1000|0.33202552|  PASSED  
rgb_minimum_distance|   4|     10000|    1000|0.92499783|  PASSED  
rgb_minimum_distance|   5|     10000|    1000|0.43088655|  PASSED  
    rgb_permutations|   2|    100000|     100|0.24249630|  PASSED  
    rgb_permutations|   3|    100000|     100|0.02193102|  PASSED  
    rgb_permutations|   4|    100000|     100|0.29246097|  PASSED  
    rgb_permutations|   5|    100000|     100|0.82793302|  PASSED  
      rgb_lagged_sum|   0|   1000000|     100|0.85672954|  PASSED  
      rgb_lagged_sum|   1|   1000000|     100|0.66018089|  PASSED  
      rgb_lagged_sum|   2|   1000000|     100|0.14464533|  PASSED  
      rgb_lagged_sum|   3|   1000000|     100|0.61958921|  PASSED  
      rgb_lagged_sum|   4|   1000000|     100|0.41404517|  PASSED  
      rgb_lagged_sum|   5|   1000000|     100|0.21085881|  PASSED  
      rgb_lagged_sum|   6|   1000000|     100|0.59236601|  PASSED  
      rgb_lagged_sum|   7|   1000000|     100|0.85844213|  PASSED  
      rgb_lagged_sum|   8|   1000000|     100|0.67532583|  PASSED  
      rgb_lagged_sum|   9|   1000000|     100|0.22960920|  PASSED  
      rgb_lagged_sum|  10|   1000000|     100|0.42416912|  PASSED  
      rgb_lagged_sum|  11|   1000000|     100|0.85142981|  PASSED  
      rgb_lagged_sum|  12|   1000000|     100|0.66956390|  PASSED  
      rgb_lagged_sum|  13|   1000000|     100|0.02113307|  PASSED  
      rgb_lagged_sum|  14|   1000000|     100|0.38234099|  PASSED  
      rgb_lagged_sum|  15|   1000000|     100|0.72755886|  PASSED  
      rgb_lagged_sum|  16|   1000000|     100|0.46936398|  PASSED  
      rgb_lagged_sum|  17|   1000000|     100|0.47843518|  PASSED  
      rgb_lagged_sum|  18|   1000000|     100|0.45445810|  PASSED  
      rgb_lagged_sum|  19|   1000000|     100|0.09850389|  PASSED  
      rgb_lagged_sum|  20|   1000000|     100|0.01429892|  PASSED  
      rgb_lagged_sum|  21|   1000000|     100|0.79504340|  PASSED  
      rgb_lagged_sum|  22|   1000000|     100|0.90117125|  PASSED  
      rgb_lagged_sum|  23|   1000000|     100|0.86218324|  PASSED  
      rgb_lagged_sum|  24|   1000000|     100|0.20973249|  PASSED  
      rgb_lagged_sum|  25|   1000000|     100|0.29309874|  PASSED  
      rgb_lagged_sum|  26|   1000000|     100|0.66429288|  PASSED  
      rgb_lagged_sum|  27|   1000000|     100|0.62583441|  PASSED  
      rgb_lagged_sum|  28|   1000000|     100|0.86432468|  PASSED  
      rgb_lagged_sum|  29|   1000000|     100|0.99449190|  PASSED  
      rgb_lagged_sum|  30|   1000000|     100|0.30593771|  PASSED  
      rgb_lagged_sum|  31|   1000000|     100|0.03909729|  PASSED  
      rgb_lagged_sum|  32|   1000000|     100|0.92391541|  PASSED  
     rgb_kstest_test|   0|     10000|    1000|0.27848827|  PASSED  
     dab_bytedistrib|   0|  51200000|       1|0.99849294|   WEAK   
             dab_dct| 256|     50000|       1|0.76828849|  PASSED  
Preparing to run test 207.  ntuple = 0
        dab_filltree|  32|  15000000|       1|0.92608225|  PASSED  
        dab_filltree|  32|  15000000|       1|0.29066666|  PASSED  
Preparing to run test 208.  ntuple = 0
       dab_filltree2|   0|   5000000|       1|0.26840219|  PASSED  
       dab_filltree2|   1|   5000000|       1|0.66679931|  PASSED  
Preparing to run test 209.  ntuple = 0
        dab_monobit2|  12|  65000000|       1|0.06439569|  PASSED 
```

### CODE REVIEW

**Comment by moodmosaic** [comment]
In case you find https://github.com/hedgehogqa/haskell-hedgehog/issues/191#issuecomment-391209131 *tl;dr*, our `from`  doesn't check the γ value *at all*―if γ is bad it leaves it as-is.

Now, once you fix `from` according to the paper

```diff
@@ -100,7 +100,7 @@ random =
 --
 from :: Word64 -> Seed
 from x =
-  Seed x goldenGamma
+  Seed (mix64 x) (mixGamma (x + goldenGamma))
```

image

you *have* to also 'fix' `mixGamma` otherwise you end up with weak γs:

```diff
@@ -192,7 +192,7 @@ mixGamma x =
     y = mix64variant13 x .|. 1
     n = popCount $ y `xor` (y `shiftR` 1)
   in
-    if n >= 24 then
+    if n < 24 then
       y `xor` 0xaaaaaaaaaaaaaaaa
     else
       y
```

The 'bug' in the paper is where it does `n >= 24` where it should be the opposite.

**Comment by Lysxia** [comment]
A "bad" `mixGamma` also affects `split`, I think that's the more important part of the issue.

**Comment by moodmosaic** [comment]
Sure, these changes are what we need here on this PR.

**Comment by moodmosaic** [comment]
/cc @jystic @thumphries 

Once we merge this, I'll go and fix the one we have in the F# version. :unicorn:

**Comment by jystic** [comment]
:100: from me, feel free to merge

**Pull request merged**
