### PR TITLE
Use bors on pull requests

### PR DESCRIPTION
**Pull request by justanotherdot**
Hiya :wave: !

Had a chat with @jystic about bringing on bors for in-work Rust port of hedgehog over at  https://github.com/justanotherdot/rust-hedgehog. Seems like integrating it was surprisingly simple and this is the followup PR for integrating it upstream.

### CODE REVIEW

**Comment by justanotherdot** [comment]
Ah, looks like I've left out appveyor, I'll add that in, too.

**Comment by moodmosaic** [comment]
Cool! Should we get the Rust port under Hedgehog QA at some point

**Comment by justanotherdot** [comment]
> Cool! Should we get the Rust port under Hedgehog QA at some point

yeah, still chipping away at it slowly :sweat_smile: 

Looks like we may need to troubleshoot a tiny bit here. The comment Jacob made should have triggered a run for bors plus merged the PR on success and deleted the branch, so not sure what's up. I'll let Jacob. See justanotherdot/rust-hedgehog#20 for an example

**Comment by jystic** [comment]
ah, was stuck on the enter password page

**Comment by justanotherdot** [comment]
I wonder if we need to kick it with an empty commit or something if it’s
now integrated?

**Comment by jystic** [comment]
maybe I need to merge so it's on master?

**Comment by justanotherdot** [comment]
nice, he's alive!

**Pull request merged**
