### PR TITLE
Depend on `semigroups`

### PR DESCRIPTION
**Pull request by LightAndLight**
Conditional dependency on `semigroups` causes some problems for tools that don't know now to deal with `if`s in cabal files. I can't build `hegdgehog` on the `ghc7102` or `ghc7103` package sets, because the tools don't know how to account for the conditional dependency. It's okay to just always depend on semigroups - see https://qfpl.io/posts/semigroups/

Please [squash this PR](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) when you merge it :)

### CODE REVIEW

**Comment by LightAndLight** [comment]
I'm not sure why the tests have failed. I'll look into it later

**Comment by gwils** [comment]
It looks like the jobs timed out.

**Comment by thumphries** [comment]
That's interesting, which tool fails to understand Cabal files? `cabal2nix` or something? Does that cause problems more widely? Lots of packages use conditionals...

This seems harmless, we should probably merge it given the additional context.

(I don't have the perms, you will have to wait a little longer)

**Comment by nhibberd** [comment]
> It's okay to just always depend on semigroups

This is still adding a redundant dependency for > 8

**Comment by LightAndLight** [comment]
@thumphries Yeah, it's `cabal2nix`. It currently just ignores conditional dependencies.
@nhibberd Okay. Is one of the goals of this project to minimize the number of external dependencies? I use GHC8+, and the thought of an extra dependency doesn't bother me.

**Comment by LightAndLight** [comment]
> In any case this is a Cassava kind of situation

Yeah I guess it is, although I wouldn't kick up such a fuss if you said no ;)

**Comment by thumphries** [comment]
Sorry that took so long. Perms sorted now

**Pull request merged**
