### PR TITLE
Support primitive 0.9

### LINKED ISSUE #508: accept primitive-0.9
This new breaking release of primitive is currently excluded by bounds in the hedgehog package.

[Changelog for primitive-0.9](https://hackage.haskell.org/package/primitive-0.9.0.0/changelog)

Stackage issue:
* https://github.com/commercialhaskell/stackage/issues/7138

### PR DESCRIPTION
**Pull request by Vekhir**
@moodmosaic 
Builds and tests fine. Closes #508

### CODE REVIEW

**Comment by moodmosaic** [comment]
Thank you! Merging right after all checks are finished successfully.

**Comment by Vekhir** [comment]
One job was cancelled without further information (MacOS / GHC 8.10.7 / Cabal 3.10.1.0). Try again or merge anyway?

**Comment by moodmosaic** [comment]
Merged, and about to do a hackage revision in the next few hours. 🎉

**Comment by Vekhir** [comment]
Thanks for merging!

**Comment by moodmosaic** [comment]
Published new [revision](https://hackage.haskell.org/package/hedgehog-1.4/revisions/) for [hedgehog-1.4](https://hackage.haskell.org/package/hedgehog-1.4). It will be available to users as soon as they update their package index (e.g. `cabal update`).

* Changed the library component's library dependency on `primitive` from

  ```
  >=0.6 && <0.9
  ```
  to
  ```
  >=0.6 && <0.10
  ```

**Pull request merged**
