### PR TITLE
Fixes for ghc-8.8

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by sjakobi** [comment]
AppVeyor complains about `haddock` missing with GHC-8.6.4:

```
%CABAL% v2-haddock -w %HC% %TEST% %BENCH% all
Build profile: -w ghc-8.6.4 -O1
In order, the following will be built (use -v for more details):
 - hedgehog-1.0 (lib) (ephemeral targets)
 - hedgehog-quickcheck-0.1.1 (lib) (dependency rebuilt)
 - hedgehog-example-0 (lib) (dependency rebuilt)
Preprocessing library for hedgehog-1.0..
Building library for hedgehog-1.0..
cabal.exe: The program 'haddock' version >=2.0 is required but it could not be
found.
cabal.exe: Failed to build documentation for hedgehog-1.0 (which is required
by hedgehog-example-0).
Command exited with code 1
```

But I don't see how that could be related to the changes here. :+1:

**Comment by newhoggy** [comment]
I've bumped the lower bounds for `checkers` dependency, so it's good to go.

**Comment by erikd** [comment]
Didn't see this. I have PR #319 which updates travis and appveyor CI builds are well.

**Comment by newhoggy** [comment]
Closing in favour of https://github.com/hedgehogqa/haskell-hedgehog/pull/319

**Pull request closed without merging**
