### PR TITLE
Allow GHC 9.8

### PR DESCRIPTION
**Pull request by tomjaguarpaw**
Fixed version of https://github.com/hedgehogqa/haskell-hedgehog/pull/503

Thanks to @ysangkok for most of the work here!

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Clearly not yet fixed, working on it!

**Comment by tomjaguarpaw** [comment]
The difference between this and https://github.com/hedgehogqa/haskell-hedgehog/pull/503 is that this one puts the warning disablement in the top-level `cabal.project`. I guess that's where it needs to be to be picked up correctly.

**Comment by tomjaguarpaw** [comment]
OK, fixed now.

**Comment by ysangkok** [comment]
Ah thanks, this seems better since it avoids adding the new `cabal.project`file. Though I don't actually understand why it would abort compilation, since I don't see `-Werror` anywhere and surely that wouldn't be the default.

**Review by moodmosaic — APPROVED** [review]
LGTM ✅

**Comment by moodmosaic** [comment]
Thank you, @ysangkok and @tomjaguarpaw 👍

**Comment by moodmosaic** [comment]
Of course 👍 It’s planned for this week.

**Comment by moodmosaic** [comment]
Published [new revision](https://hackage.haskell.org/package/hedgehog-1.4/revisions/) for [hedgehog-1.4](https://hackage.haskell.org/package/hedgehog-1.4) as per https://github.com/hedgehogqa/haskell-hedgehog/issues/502#issuecomment-1772348179 🦔

**Comment by tomjaguarpaw** [comment]
Thanks!

**Pull request merged**
