### PR TITLE
Added a SizeLimit configuration option

### PR DESCRIPTION
**Pull request by etorreborre**
and bumped other "limit" options to Int64.

Hey there. I am currently working on integrating "enumerative testing" to Hedgehog where, instead of randomly selecting values out of a given range we enumerate them exhaustively for small size (ala SmallCheck) then switch to random selection when there are too many combinations. I think that this is a way to get a nice coverage, especially of "business" data structures which are not recursive. 

However in order to integrate those `Enumerates` (coming from the `testing-feat` package) as generators we need to be able to "index" into them. However the only two parameters passed to a `GenT` are `Size` and `Seed`. I would like to use `Size` for my indexing into an enumeration so I need it to be able to go from `0` to a configured value.

So I am proposing to be able to have the currently hard-coded `99` size value as a configuration option, which shouldn't hurt any current user. At the same time, those enumerations can be quite large so the size needs to be bounded and `Int64` is a good candidate for that. I know this has some memory implications but I don't think that they matter much for test execution.

Here is an example of how I am using all of this to enumerate the values of a datatype: https://github.com/etorreborre/registry-hedgehog/blob/testing-feat/test/Test/Data/Registry/TestingFeatSpec.hs#L39

### CODE REVIEW

**Comment by jacobstanley** [comment]
> At the same time, those enumerations can be quite large so the size needs to be bounded and `Int64` is a good candidate for that.

fwiw `Int` = `Int64` on basically every platform, I think it's even 64-bit on windows now

`Int` is also bounded

**Comment by symbiont-eric-torreborre** [comment]
Of course, I'm silly. I will fix that in the PR.

Otherwise what do you think of this Size parameter?

**Comment by symbiont-eric-torreborre** [comment]
Removed the `Int64` in a fixup commit.

**Comment by etorreborre** [comment]
> Otherwise what do you think of this Size parameter?

@jacobstanley ping, in case you didn't see my question

**Comment by jacobstanley** [comment]
I'm nervous about possible side effects that we're not aware of, but I suppose it's opt-in as you point out

All the generators assume size is only from 0-99 so i'm slightly concerned it may have unintended side effects? Not sure how we can check everything doesn't go crazy! But yeah hopefully we can get this through.

So, if you had access to just the current test number would that also solve your issue? I actually wanted this the other day.

**Comment by symbiont-eric-torreborre** [comment]
> So, if you had access to just the current test number would that also solve your issue? 

If that was accessible as a parameter to `runGenT` in addition to size and seed yes that would work.

**Comment by symbiont-eric-torreborre** [comment]
This might be a bigger change in the code base though? Also I'm curious, what was your use case?

**Comment by symbiont-eric-torreborre** [comment]
@jacobstanley If you're onboard with this idea, I can close this PR and start another one.

**Comment by jacobstanley** [comment]
Yeah that is a huge change! I didn't think of that. Hmm, not sure I'm ready to commit yet but it would be handy.

I want to add golden testing to hedgehog and I want to produce a different output file for each test. I could use the size, but that would limit me to 100 files, which is probably plenty.

**Comment by symbiont-eric-torreborre** [comment]
Actually `runGenT` is used 19 times in `Gen.hs` and `GenT` 13 times. It seems that it's all located to one file.  This might not be a big deal, except maybe the lack of backward compatibility (at the same time this is an internal API).

**Comment by etorreborre** [comment]
https://github.com/etorreborre/haskell-hedgehog/tree/gen-with-tests-number

@jacobstanley if you want to get a feel for the changes involved in using the number of tests in a generator. Note that:

 - I had to put the `TestCount` into its own file
 - I arbitrarily passed `0` to `evalGen`, maybe we should add another function `evalGenAt :: TestCount ...` taking the tests number as a parameter as well

BTW github won't let me create a PR for now, error 500 👎

**Comment by etorreborre** [comment]
The PR for using the test count is here: https://github.com/hedgehogqa/haskell-hedgehog/pull/307

**Comment by etorreborre** [comment]
I'm going to close this PR for now and just leave the other PR where we can access the test count.

**Pull request closed without merging**
