### PR TITLE
Cabal.project

### PR DESCRIPTION
**Pull request by gwils**
This lets you build all three packages from the top level with `cabal new-build all`
I've also added the new-build artifacts to the .gitignore

### CODE REVIEW

**Comment by thumphries** [comment]
Thanks George! :hocho:

**Comment by moodmosaic** [comment]
Is `cabal.project` supposed to play nice with `stack` or only with `mafia`? I'm not the biggest fan of `stack` but it's been widely used so I thought I should give it a shot:

```
$ stack init --solver
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- hedgehog-example/
- hedgehog-quickcheck/
- hedgehog/

Selecting the best among 12 snapshots...

* Partially matches lts-10.4
    mmorph version 1.1.0 found
        - hedgehog-example requires >=1.0 && <1.1
    temporary-resourcet not found
        - hedgehog-example requires >=0.1 && <0.2

* Partially matches nightly-2018-02-08
    mmorph version 1.1.0 found
        - hedgehog-example requires >=1.0 && <1.1
    temporary-resourcet not found
        - hedgehog-example requires >=0.1 && <0.2

* Partially matches lts-9.21
    temporary-resourcet not found
        - hedgehog-example requires >=0.1 && <0.2

* Partially matches lts-8.24
    temporary-resourcet not found
        - hedgehog-example requires >=0.1 && <0.2

* Partially matches lts-7.24
    temporary-resourcet not found
        - hedgehog-example requires >=0.1 && <0.2

* Partially matches lts-6.35
    temporary-resourcet not found
        - hedgehog-example requires >=0.1 && <0.2
    wl-pprint-annotated not found
        - hedgehog requires >=0.0 && <0.2

* Partially matches lts-5.18
    temporary-resourcet not found
        - hedgehog-example requires >=0.1 && <0.2
    wl-pprint-annotated not found
        - hedgehog requires >=0.0 && <0.2

* Partially matches lts-4.2
    temporary-resourcet not found
        - hedgehog-example requires >=0.1 && <0.2
    wl-pprint-annotated not found
        - hedgehog requires >=0.0 && <0.2

* Partially matches lts-3.22
    concurrent-output not found
        - hedgehog requires >=1.7 && <1.11
    temporary-resourcet not found
        - hedgehog-example requires >=0.1 && <0.2
    wl-pprint-annotated not found
        - hedgehog requires >=0.0 && <0.2

* Rejected lts-2.22
    ghc-7.8.4 cannot be used for these packages:
        - hedgehog
    template-haskell version 2.9.0.0 found
        - hedgehog requires >=2.10 && <2.14

* Rejected lts-1.15
    ghc-7.8.4 cannot be used for these packages:
        - hedgehog
    template-haskell version 2.9.0.0 found
        - hedgehog requires >=2.10 && <2.14

* Rejected lts-0.7
    ghc-7.8.3 cannot be used for these packages:
        - hedgehog
    template-haskell version 2.9.0.0 found
        - hedgehog requires >=2.10 && <2.14

Selected resolver: lts-9.21
*** Resolver lts-9.21 will need external packages: 
    temporary-resourcet not found
        - hedgehog-example requires >=0.1 && <0.2

Using resolver: lts-9.21

Warning: Installed version of cabal-install (2.0.0.1) is newer than stack has been tested with.  If you run into difficulties, consider downgrading.
         
Using compiler: ghc-8.0.2
Asking cabal to calculate a build plan...
Trying with packages from lts-9.21 as hard constraints...
The following lines from cabal-install output could not be parsed: 
ansi-terminal-0.6.3.1 (latest: 0.8.0.1) (via: hedgehog-0.5.2
concurrent-output-1.9.2) (new package)
mtl-2.2.1 (via: hedgehog-example-0 hedgehog-0.5.2 resourcet-1.1.9
constraints-0.9.1 exceptions-0.8.3 mmorph-1.0.9 parsec-3.1.11) (new package)
primitive-0.6.2.0 (latest: 0.6.3.0) (via: hedgehog-0.5.2 hashtables-1.2.2.1
tf-random-0.5 vector-0.12.0.1) (new package)
semigroups-0.18.3 (latest: 0.18.4) (via: hedgehog-0.5.2 hedgehog-0.5.2) (new
package)
stm-2.4.4.1 (latest: 2.4.5.0) (via: hedgehog-0.5.2 concurrent-output-1.9.2
monad-control-1.0.2.2 exceptions-0.8.3 transformers-base-0.4.4 async-2.1.1.1)
(new package)
text-1.2.2.2 (latest: 1.2.3.0) (via: hedgehog-example-0 hedgehog-0.5.2
hedgehog-0.5.2 concurrent-output-1.9.2 hashable-1.2.6.1 parsec-3.1.11
wl-pprint-annotated-0.1.0.0) (new package)
transformers-compat-0.5.1.4 (via: resourcet-1.1.9 monad-control-1.0.2.2
constraints-0.9.1 exceptions-0.8.3 mmorph-1.0.9 transformers-base-0.4.4) (new
package)
pretty-show-1.6.15 (latest: 1.6.16) (via: hedgehog-example-0 hedgehog-0.5.2
hedgehog-0.5.2) (new package)
async-2.1.1.1 (latest: 2.2.1) (via: hedgehog-0.5.2 lifted-async-0.9.3.2
concurrent-output-1.9.2) (new package)
transformers-base-0.4.4 (via: hedgehog-0.5.2 lifted-async-0.9.3.2
resourcet-1.1.9 lifted-base-0.2.3.11 monad-control-1.0.2.2) (new package)
mmorph-1.0.9 (latest: 1.1.0) (via: hedgehog-example-0 hedgehog-0.5.2
resourcet-1.1.9) (new package)
exceptions-0.8.3 (via: hedgehog-0.5.2 temporary-resourcet-0.1.0.0
resourcet-1.1.9 concurrent-output-1.9.2) (new package)
QuickCheck-2.9.2 (latest: 2.11.3) (via: hedgehog-example-0
hedgehog-quickcheck-0.1) (new package)
monad-control-1.0.2.2 (via: hedgehog-0.5.2 lifted-async-0.9.3.2
resourcet-1.1.9 lifted-base-0.2.3.11) (new package)
resourcet-1.1.9 (latest: 1.2.0) (via: hedgehog-example-0 hedgehog-0.5.2
temporary-resourcet-0.1.0.0) (new package)
hedgehog-0.5.2 *test (via: hedgehog-example-0 hedgehog-example-0
hedgehog-quickcheck-0.1) (new package)
hedgehog-quickcheck-0.1 (via: hedgehog-example-0 hedgehog-example-0) (new
package)
CallStack (from HasCallStack):
  error, called at src/Stack/Solver.hs:173:16 in stack-1.6.3-29yGLWFZzMc4kc0GGcUpok:Stack.Solver
```

**Comment by thumphries** [comment]
`cabal.project` files are for Cabal >= 2.0. I don't think Stack understands them. Mafia doesn't understand them either. I recommend building with `cabal new-build all` as George suggests, or with mafia.

Those errors look weird. You might have an old version of Stack? Try again with 1.6.3 and it might work

**Comment by moodmosaic** [comment]
They are, indeed, weird. I'm using `stack` 1.6.3

```
$ stack --version
Version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0
```
I'll let you know if I find out what causes those errors.

**Pull request merged**
