### PR TITLE
Bump upper bounds for resourcet and primitive.

### PR DESCRIPTION
**Pull request by shlevy**
Would be great to get new releases/revisions with this change.

### CODE REVIEW

**Review by moodmosaic — APPROVED** [review]
👍 LGTM

Have to check why CI keeps failing.

**Comment by ysangkok** [comment]
> Have to check why CI keeps failing.

#482 explains the problem and fixes it.

**Comment by michaelpj** [comment]
It would be nice to get this released, or maybe just a revision?

**Comment by andreasabel** [comment]
I made a revision on hackage: https://hackage.haskell.org/package/hedgehog-1.2/revisions/

However, `master` has changes that need a release for shipping.

**Pull request merged**
