### PR TITLE
Exposes more state machine functionality.

### PR DESCRIPTION
**Pull request by dalaing**
This allows us to do fancier generation than we can do with just `sequential`.

I'm using this to allow for explicitly generating actions over phases - the first phase sets up some account, the second phases uses the accounts to add data to the application under test, and the third phase is reading the data.

(I'm mostly interested in using this for benchmarking, by fixing a seed and size and having some setup phases run before the actual benchmark phases)

### CODE REVIEW

**Review by moodmosaic — COMMENTED** [review]
LGTM 👍

Can we include some example/test showing what’s possible? That’d be great to have, so the users know how to use the stuff we’re exporting.

**Comment by dalaing** [comment]
For sure. I'll try to get some examples together in the next week or so.

**Comment by dalaing** [comment]
It turns out I needed more constraints inside of the Command constructor, and had to copy-and-paste huge chunks of State.hs to get my benchmarking to go. Should I close this? Or leave it in case others might need it? I can always recreate this and open a new PR if I end up with a new concrete use case for it.

**Comment by moodmosaic** [comment]
Thank you for your contribution! We appreciate your effort. 🙏 💯 

Regarding the PR, since it sounds like the changes might not be needed in the current scope of the project, and you're also considering different approaches, I think it would be best to close this PR for now. 

Please do feel free to reopen it or submit a new PR if you find that these changes become relevant in the future or if you have other enhancements to suggest.

Thanks again for your willingness to contribute, and looking forward to any future contribution. 🚀

**Pull request closed without merging**
