### PR TITLE
Bump time upper bound version

### PR DESCRIPTION
**Pull request by shinzui**
It builds and tests run fine.

### CODE REVIEW

**Comment by shinzui** [comment]
Fixes #430

**Review by moodmosaic — COMMENTED** [review]
Keep in mind `time` 1.12 supports GHC >= 8.8, 8.10, 9.0

**Comment by moodmosaic** [comment]
@jacobstanley what do you think?

**Comment by shinzui** [comment]
Thanks. Is it possible to release a new version?

**Comment by moodmosaic** [comment]
Perhaps we can, however it'll be faster with a package revision on hackage.

**Comment by moodmosaic** [comment]
@shinzui, the new revision for `hedgehog-1.0.5` has been published. You'll have to update your package index (e.g. cabal update).

---

* Changed the library component's library dependency on `time` from

```
>=1.4 && <1.10
```
to
```
>=1.4 && <1.13
```

**Comment by shinzui** [comment]
Thank you.

**Pull request merged**
