### PR TITLE
Remove outdated point releases of GHC from Travis

### PR DESCRIPTION
**Pull request by gwils**

### CODE REVIEW

**Comment by nhibberd** [comment]
I don't see any harm in leaving these as current builds? Unless I am missing something

**Comment by gwils** [comment]
Travis will only build so many at a time, so in the interest of prompt feedback on my branches and pull requests, I'd prefer to remove obsolete point versions.
It's not a huge deal either way.

**Comment by thumphries** [comment]
Travis does 5 builds at a time. However we take between two days and three months to look at PRs, so it probably doesn't matter much

**Comment by moodmosaic** [comment]
Yes, I think we should leave those in for now.

**Comment by gwils** [comment]
Ok, I'll close this and add those versions to #149

**Pull request closed without merging**
