### PR TITLE
Release 1.0

### PR DESCRIPTION
**Pull request by jacobstanley**
<div align="center">

### CODE REVIEW

**Comment by jacobstanley** [comment]
_Updated [README.md](https://github.com/jacobstanley/haskell-hedgehog/blob/topic/release-1.0/README.md), the GitHub diff mangles it._

**Comment by moodmosaic** [comment]
:rocket:

**Comment by moodmosaic** [comment]
New README looks awesome, specially the grey logo at the bottom :guitar: :fire:

**Comment by moodmosaic** [comment]
<div align="center">

**Pull request merged**
